### ISSUE TITLE
Possible bug in the deployment

### ISSUE THREAD

**Issue by bpappin** [GuilhE/CircularProgressView#21]
## Describe the bug
after adding the dependency:

`implementation 'com.github.guilhe:circular-progress-view:2.0.0'`

I get an error message from gradle saying:

`Failed to resolve: null:unspecified:null`

**Comment by GuilhE** [comment]
Hello, just to add more information:

> Execution failed for task ':app:checkDevDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
   > Could not find null:unspecified:null.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/null/unspecified/null/unspecified-null.pom
       - https://jcenter.bintray.com/null/unspecified/null/unspecified-null.pom
       - https://jitpack.io/null/unspecified/null/unspecified-null.pom
     Required by:
         project :app > com.github.guilhe:circular-progress-view:2.0.0
> Possible solution:
>  - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

I'll look into it :wink:

**Comment by GuilhE** [comment]
Importing from `mavenLocal()` works which makes me think the problem is not related with the `deploy.gradle` script 🤔

**Comment by GuilhE** [comment]
@bpappin please use the jitpack import, it works.
I can't understand why jcenter/maven doesn't (since it worked for all other versions).

[![](https://jitpack.io/v/GuilhE/CircularProgressView.svg)](https://jitpack.io/#GuilhE/CircularProgressView)

**Comment by GuilhE** [comment]
Running: ` ./gradlew assembleDebug --refresh-dependencies` I could get the dependency (I've removed jcenter() from my gradle files) without any problems.
