### ISSUE TITLE
Semi circle progress

### ISSUE THREAD

**Issue by PeriyaCC** [GuilhE/CircularProgressView#22]
##  How to show a semi-circle instead of a full circle?

**Comment by GuilhE** [comment]
This library only allows 0-100% in a circle shape.
If you want to mimic a semi-circle you can disable the background, add 50% to have half circle completed and then change the `startingAngle` to position the "semi-circle". If you want a 0-100% logic in a semi-circle shape you'll have to map the values from [0-100] into a range of [0-50].
