### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by wilinz** [GuilhE/CircularProgressView#23]
Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.github.guilhe:circular-progress-view:2.0.0] C:\Users\wilinz\.gradle\caches\transforms-3\4a88ba944255ebbdfe19365beb85bd41\transformed\circular-progress-view-2.0.0\AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 23,
		or use tools:overrideLibrary="com.github.guilhe.views.circularprogress" to force usage (may lead to runtime failures)

**Comment by GuilhE** [comment]
Hello @wilinz , I won't be lowering the SDK version so the best bet you can use for now is:
- Fork the project, lower the version and use jitpack to publish it under your fork;
- Add `tools:overrideLibrary="com.github.guilhe.views.circularprogress"` in your manifest and see if nothing breaks.
- Increase your project's mindSdk to at least 23
